---
title: snapfigs blog
author: dogmustard
email: jonny.davis@hey.com
description: snapfigs aim to merge the worlds of physical and digital collectibles in a fun and unique way. this is the place to learn all about them.
baseurl: ''
url: http://blog.snapfigs.hns.to/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
