---
title: SnapFigs Blog
author: dogmustard
email: support@forestry.io
description: ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks
  feature. This theme provides a set of page-level components and a pre-configured
  Forestry Blocks UI that will empower content editors to construct their own webpages.
baseurl: "/"
url: http://blog.snapfigs.hns.to/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
menu:
  main:
    weight: 2
    title: Updates
